WebDongHo/Controllers/HomeUserController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDongHo.Models;
using PagedList;
namespace WebDongHo.Controllers
{
    public class HomeUserController : Controller
    {
        DBDongHoDataContext data = new DBDongHoDataContext();
        // GET: HomeUser
        
        public List<SanPham> SanPhamMoi(int count)
        {
            return data.SanPhams.OrderByDescending(a => a.NgayCapNhap).Take(count).ToList();
        }
        public ActionResult Index()
        {
            var spmoi = SanPhamMoi(4);       
            return View(spmoi);
        }
        public IEnumerable<SanPham> ListAllPage(string searchString, int page, int pageSize)
        {
        
            IQueryable<SanPham> model = data.SanPhams;
            if (!String.IsNullOrEmpty(searchString))
            {
                model = model.Where(s => s.TenSanPham.Contains(searchString) || s.MoTaNgan.Contains(searchString));
            }
            return model.OrderByDescending(x => x.NgayCapNhap).ToPagedList(page, pageSize);
        }
        public ActionResult SPNu()
        {
            var clients = from c in data.SanPhams
                          where c.TenSanPham.Contains("Nữ")
                          select c;
            return PartialView(clients);
        }

        public ActionResult SPNam()
        {
            var clients = from c in data.SanPhams
                          where c.TenSanPham.Contains("Nam")
                          select c;
            return PartialView(clients);
        }
        public ActionResult DanhMucSanPham()
        {
            var danhmuc = from dm in data.DanhMucSanPhams select dm;
            return PartialView(danhmuc);
        }
        public ActionResult DanhMucThuongHieu(int id)
        {
            var sp = from s in data.SanPhams
                     where s.MaDanhMuc == id
                     select s;
            ViewBag.TenTH = (from th in data.DanhMucSanPhams
                             where th.MaDanhMuc == id
                             select th);
            return View(sp);

        }
        public ActionResult Detail(int id)
        {
            var sp = from s in data.SanPhams
                     where s.MaSanPham == id
                     select s;
            
            ViewBag.SP_Khac = (from c in data.SanPhams
                               where c.MaDanhMuc != id                        
                               select c).ToList().Take(4);
            return View(sp.Single());
        }

        [HttpGet]
        public ActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Contact(FormCollection f,LienHe lh)
        {
            var Hoten = f["HoTen"];
            var Email = f["Email"];
            var Chude = f["ChuDe"];
            var Noidung = f["NoiDung"];
            if(String.IsNullOrEmpty(Hoten))
            {
                ViewData["Loi1"] = "Họ tên không được để trống";
            }
            else if (String.IsNullOrEmpty(Email))
            {
                ViewData["Loi2"] = "Email không được để trống";
            }
            else if (String.IsNullOrEmpty(Chude))
            {
                ViewData["Loi3"] = "Chủ đề không được để trống";
            }
            else if (String.IsNullOrEmpty(Noidung))
            {
                ViewData["Loi4"] = "Nội dung không được để trống";
            }
            else
            {
                lh.HoTen = Hoten;
                lh.Email = Email;
                lh.ChuDe = Chude;
                lh.NoiDung = Noidung;
                data.LienHes.InsertOnSubmit(lh);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Contact();  
        }        
        public ActionResult ThuongHieu(/*string searchString, int page = 1, int pageSize = 10*/ int? page)
        {
            var sp = from s in data.SanPhams select s;


            int pageNumber = (page ?? 1);
            int pageSize = 8;

            //ViewBag.TimKiem = ListAllPage(searchString, page, pageSize);

            //return View(sp);
            
            return View(data.SanPhams.ToList().OrderBy(n => n.MaSanPham).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Search(string searching)
        {
            //Lấy ra danh sách sản phẩm từ chuỗi tìm kiếm truyền vào
            var sp = from s in data.SanPhams select s;     
            ViewBag.TuKhoa = searching;

            return View(data.SanPhams.Where(x=>x.TenSanPham.Contains(searching) ||  searching == null).ToList());
        }
        public ActionResult Nu()
        {
            var clients = from c in data.SanPhams
                          where c.TenSanPham.Contains("Nữ")
                          select c;
            return View(clients);
        }

        public ActionResult Nam()
        {
            var clients = from c in data.SanPhams
                          where c.TenSanPham.Contains("Nam")
                          select c;
            return View(clients);
        }
        public ActionResult TinTuc()
        {     
            return View();
        }

        public ActionResult TinTuc1()
        {
            return View();
        }

        public ActionResult TinTuc2()
        {
            return View();
        }

        public ActionResult TinTuc3()
        {
            return View();
        }

        public ActionResult TinTuc4()
        {
            return View();
        }

        public ActionResult TinTuc5()
        {
            return View();
        }

        public ActionResult TinTuc6()
        {
            return View();
        }
        public ActionResult Payment()
        {
            //request params need to request to MoMo system
            string endpoint = "https://test-payment.momo.vn/gw_payment/transactionProcessor";
            string partnerCode = "MOMO2C5U20210720";
            string accessKey = "xTyRu9YtM0I082Z7";
            string serectkey = "bNjdi5w3IoG1fhVZbFPCDy5dUkfLZH0i";
            string orderInfo = "test";
            string returnUrl = "https://localhost:44324/HomeUser/ConfirmPaymentClient";
            string notifyurl = "https://localhost:44324/HomeUser/SavePayment"; 

            string amount = TongTien().ToString();
            string orderid = DateTime.Now.Ticks.ToString();
            string requestId = DateTime.Now.Ticks.ToString();
            string extraData = "";

            //Before sign HMAC SHA256 signature
            string rawHash = "partnerCode=" +
                partnerCode + "&accessKey=" +
                accessKey + "&requestId=" +
                requestId + "&amount=" +
                amount + "&orderId=" +
                orderid + "&orderInfo=" +
                orderInfo + "&returnUrl=" +
                returnUrl + "&notifyUrl=" +
                notifyurl + "&extraData=" +
                extraData;

            Momo crypto = new Momo();
            //sign signature SHA256
            string signature = crypto.signSHA256(rawHash, serectkey);

            //build body json request
            JObject message = new JObject
            {
                { "partnerCode", partnerCode },
                { "accessKey", accessKey },
                { "requestId", requestId },
                { "amount", amount },
                { "orderId", orderid },
                { "orderInfo", orderInfo },
                { "returnUrl", returnUrl },
                { "notifyUrl", notifyurl },
                { "extraData", extraData },
                { "requestType", "captureMoMoWallet" },
                { "signature", signature }

            };

            string responseFromMomo = PaymentRequest.sendPaymentRequest(endpoint, message.ToString());

            JObject jmessage = JObject.Parse(responseFromMomo);

            return Redirect(jmessage.GetValue("payUrl").ToString());
        }
        public List<Giohang> Laygiohang()
        {
            List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            if (lstGiohang == null)
            {
                lstGiohang = new List<Giohang>(); Session["Giohang"] = lstGiohang;
            }
            return lstGiohang;
        }
        public int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                iTongSoLuong = lstGiohang.Sum(n => n.iSoluong);
            }
            return iTongSoLuong;
        }
        public double TongTien()
        {
            double iTongTien = 0;
            List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                iTongTien = lstGiohang.Sum(n => n.dThanhtien);
            }
            return iTongTien;
        }


        public ActionResult ConfirmPaymentClient()
        {
            if (!Request.QueryString["errorCode"].Equals("0"))
            {
                Session["or"] = null;
                Session["lst"] = null;
                ViewBag.mess = "Thanh Toán thất bại";
            }
            else
            {
                ViewBag.mess = "Thanh toán thành công";
                SavePayment();
                Session["Giohang"] = null;
            }
            return View();
        }
     
        public void SavePayment()
        {         
            //DONDATHANG order = (DONDATHANG)Session["or"];
            //data.DONDATHANGs.InsertOnSubmit(order);
            //data.SubmitChanges();
            //List<CHITIETDONHANG> lst = (List<CHITIETDONHANG>)Session["lst"];
            //foreach (var item in lst)
            //{
            //    item.MaDonHang = order.MaDonHang;
            //    data.CHITIETDONHANGs.InsertOnSubmit(item);

WebDongHo/Controllers/ThuongHieuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDongHo.Models;

namespace WebDongHo.Controllers
{
    public class ThuongHieuController : Controller
    {
        // GET: ThuongHieu
        DBDongHoDataContext db = new DBDongHoDataContext();
        public ActionResult Index()
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            return View(db.DanhMucSanPhams.ToList());
        }
        public ActionResult Create()
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else          
                return View();
        }
        [HttpPost,ActionName("Create")]
        public ActionResult Them(DanhMucSanPham th)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                db.DanhMucSanPhams.InsertOnSubmit(th);
                db.SubmitChanges();
                return RedirectToAction("Index", "ThuongHieu");
            }
        }
        public ActionResult Edit(int id)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                var thuonghieu = from th in db.DanhMucSanPhams where th.MaDanhMuc == id select th;
                return View(thuonghieu.SingleOrDefault());
            }
        }
        [HttpPost,ActionName("Edit")]
        public ActionResult Sua(int id)
        {
            {
                DanhMucSanPham dm = db.DanhMucSanPhams.Where(n => n.MaDanhMuc == id).SingleOrDefault();
                UpdateModel(dm);
                db.SubmitChanges();
                return RedirectToAction("Index", "ThuongHieu");
            }
        }
        public ActionResult Delete(int id)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                var thuonghieu = from th in db.DanhMucSanPhams where th.MaDanhMuc == id select th;
                return View(thuonghieu.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Xoa(int id)
        {
            {
                DanhMucSanPham dm = db.DanhMucSanPhams.Where(n => n.MaDanhMuc == id).SingleOrDefault();
                db.DanhMucSanPhams.DeleteOnSubmit(dm);
                db.SubmitChanges();
                return RedirectToAction("Index", "ThuongHieu");
            }
        }

    }
}

WebDongHo/Views/HomeUser/ConfirmPaymentClient.cshtml
@{
    ViewBag.Title = "ConfirmPaymentClient";
    Layout = "~/Views/Shared/_LayoutUsers.cshtml";
}
<link rel="stylesheet" href="~/Content/cart.css" />
<div id="confirm">
    <div class="container">
        <div class="confirm">
            <h2 class="confirm-alert">@ViewBag.mess</h2>
            <p>Cảm ơn quý khách đã ủng hộ shop. Đơn hàng của quý khách sẽ nhanh chóng được gửi đến đúng hẹn !</p>
            <a href="@Url.Action("Index","HomeUser")" class="btn-back">Quay Về Trang Chủ</a>
        </div>
    </div>
</div>

WebDongHo/Views/HomeUser/DanhMucSanPham.cshtml
@model IEnumerable<WebDongHo.Models.DanhMucSanPham>


@foreach (var item in Model)
{
    <li><a href="@Url.Action("DanhMucThuongHieu","HomeUser",new {id = item.MaDanhMuc })">@item.TenDanhMuc</a></li>
    
    }

WebDongHo/Views/HomeUser/DanhMucThuongHieu.cshtml
@model IEnumerable<WebDongHo.Models.SanPham>
@{
    ViewBag.Title = "DanhMucThuongHieu";
    Layout = "~/Views/Shared/_LayoutUsers.cshtml";
}

<div class="container">
    <ul style="text-align:center; color:#FFF;font-size:30px;padding-bottom:20px">
        <li>
            <a class="current">
                Hãng sản xuất @foreach (var item in ViewBag.TenTH)
                {
                    @item.TenDanhMuc
                }
            </a>
        </li>
    </ul>
    <div class="row">
        
        
        @foreach (var item in Model)
        {
            <div class="col-4">
                <a href="@Url.Action("Detail","HomeUser",new{ id=item.MaSanPham  })">
                    <img src="@item.ImgUrl" width="250" height="250" alt="@item.TenSanPham">
                    <h4>@item.TenSanPham</h4>
                    <p class="price">@String.Format("{0:0,0}", item.GiaGoc) VND</p>
                </a>
            </div>
        }

    </div>
</div>

WebDongHo/Views/HomeUser/Detail.cshtml
@model WebDongHo.Models.SanPham


@{
    ViewBag.Title = "Chi Tiết Sản Phẩm";
    Layout = "~/Views/Shared/_LayoutUsers.cshtml";
}



<link rel="stylesheet" href="~/Content/base.css" />
<link rel="stylesheet" href="~/Content/detail.css" />

<!-- Details -->
<div id="detail">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <img id="img__big" src="@Model.ImgUrl" width="400" height="400" alt="">
                <div class="images">
                    <div class="img__small">
                        <img src="@Model.ImgUrl" alt="" class="imgs active">
                        <img src="@Model.ImgUrl1" alt="" class="imgs">
                        <img src="@Model.ImgUrl2 " alt="" class="imgs">
                    </div>
                </div>
            </div>
            <div class="col-2">
                <div class="info-detail">
                    <div class="info">
                        <h2>Thông Tin Sản Phẩm</h2>
                        <h3>@Model.TenSanPham</h3>
                    </div>
                    <div class="price">
                        <h3>@String.Format("{0:0,0}", Model.KhuyenMai) VND</h3>
                        <h3>@String.Format("{0:0,0}", Model.GiaGoc) VND</h3>

                    </div>
                    <div class="tabs-info">
                        <div class="info-item active">Mô Tả</div>
                        <div class="info-item ">Thông Tin Cơ Bản</div>
                        <div class="info-item ">Xuất Xứ</div>

                    </div>
                    <div class="tabs-info-content">
                        <div class="tab-pane active">
                            <p>@Model.MoTaNgan</p>
                        </div>
                        <div class="tab-pane">
                            <p>@Model.MoTaChiTiet</p>
                        </div>
                        <div class="tab-pane">
                            <p>Đồng hồ Longines L4.860.2.11.7 là đồng hồ thời trang thuộc công ty Fossil có trụ sở tại bang Texas, của Mỹ.</p>
                        </div>
                    </div>


                    <div class="button">
                        <div class="btn">
                            <a href="@Url.Action("ThemGiohang","Giohang", new { @id = @Model.MaSanPham,@strURL=Request.Url.ToString() })" class="cart-icon">
                                <i class="fas fa-shopping-cart"></i>
                                Thêm vào giỏ
                            </a>
                        </div>
                        <div class="btn">
                            <a href="" class="buy-now">Mua Ngay</a>
                        </div>
                    </div>
                    <div style="background:#fff; margin-top: 30px"  class="fb-comments" data-href="http://dongho4aechinhhang.somee.com/" data-width="" data-numposts="10"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@*Xem thêm sản Phẩm*@

<table>
    <div class="container">
        <h2 class="title">Sản Phẩm Khác</h2>
        <div class="row">
            @foreach (var item in ViewBag.SP_Khac)
            {
                <div class="col-4">
                    <a href="@Url.Action("Detail","HomeUser",new{ id=item.MaSanPham  })">
                        <img src="@item.ImgUrl" width="250" height="250" alt="@item.TenSanPham">
                        <h4>@item.TenSanPham</h4>
                        <p class="price">@String.Format("{0:0,0}", item.GiaGoc) VND</p>
                    </a>
                </div>

            }
        </div>
    </div>

</table>


<div class="clear"></div>

WebDongHo/Views/HomeUser/Nu.cshtml
@{
    ViewBag.Title = "Nu";
    Layout = "~/Views/Shared/_LayoutUsers.cshtml";
}

@model IEnumerable<WebDongHo.Models.SanPham>



<div class="container">
    <h2 class="title">Đồng hồ nữ</h2>
    <div class="row">

        @foreach (var item in Model)
        {
            <div class="col-4">
                <a href="@Url.Action("Detail","HomeUser",new{ id=item.MaSanPham  })">
                    <img src="@item.ImgUrl" height="250" width="250" alt="@item.TenSanPham">
                    <h4>@item.TenSanPham</h4>
                    <p class="price">@String.Format("{0:0,0}", item.GiaGoc) VND</p>
                </a>
            </div>
        }
    </div>
</div>

WebDongHo/Views/HomeUser/SPNam.cshtml
@model IEnumerable<WebDongHo.Models.SanPham>


<div class="container">
    <h2 class="title">Đồng hồ nam bán chạy</h2>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-4">
                <a href="@Url.Action("Detail","HomeUser",new{ id=item.MaSanPham  })">
                    <img src="@item.ImgUrl" width="250" height="250" alt="@item.TenSanPham">
                    <h4>@item.TenSanPham</h4>
                    <p class="price">@String.Format("{0:0,0}", item.GiaGoc) VND</p>
                </a>
            </div>
        }

    </div>
</div>

WebDongHo/Views/HomeUser/SPNu.cshtml
@model IEnumerable<WebDongHo.Models.SanPham>



<div class="container">
    <h2 class="title">Đồng hồ nữ bán chạy</h2>
    <div class="row">

        @foreach (var item in Model)
        {
            <div class="col-4">
                <a href="@Url.Action("Detail","HomeUser",new{ id=item.MaSanPham  })">
                    <img src="@item.ImgUrl" height="250" width="250" alt="@item.TenSanPham">
                    <h4>@item.TenSanPham</h4>
                    <p class="price">@String.Format("{0:0,0}", item.GiaGoc) VND</p>
                </a>
            </div>
        }
    </div>
</div>

WebDongHo/Views/HomeUser/Search.cshtml
@model IEnumerable<WebDongHo.Models.SanPham>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutUsers.cshtml";
}

<table>
</table>

<div style="margin: 15px 88px; padding: 10px; background: #334; display: inline-block;">
    <h3 style="text-align:center; color:#ccc; font-size:12px"> Hiện thị kết quả cho: " @ViewBag.TuKhoa " </h3>
</div>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-4">
                <a href="@Url.Action("Detail","HomeUser",new{ id=item.MaSanPham  })">
                    <img src="@item.ImgUrl" width="250" height="250" alt="@item.TenSanPham">
                    <h4>@item.TenSanPham</h4>
                    <p class="price">@String.Format("{0:0,0}", item.GiaGoc) VND</p>
                </a>
            </div>
        }
    </div>
</div>

WebDongHo/Views/HomeUser/ThuongHieu.cshtml
@using WebDongHo.Models
@using PagedList.Mvc;
@model PagedList.PagedList<WebDongHo.Models.SanPham>
@{
    ViewBag.Title = "ThuongHieu";
    Layout = "~/Views/Shared/_LayoutUsers.cshtml";
}

<table>
    <div class="container">
        <h2 class="title">Tất Cả Sản Phẩm</h2>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-4">
                    <a href="@Url.Action("Detail","HomeUser",new{ id=item.MaSanPham  })">
                        <img src="@item.ImgUrl" width="250" height="250" alt="@item.TenSanPham">
                        <h4>@item.TenSanPham</h4>
                        <p class="price">@String.Format("{0:0,0}", item.GiaGoc) VND</p>
                    </a>
                </div>
            }
        </div>
    </div>
</table>
@*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("ThuongHieu", new { page = page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
        color: #fff
    }
</style>*@



<link rel="stylesheet" href="~/Content/pagination.css" />

<!-- pagination -->
<ul class="pagination home-product__pagination">
    <li class="pagination-item">
        <a href="#" class="pagination-item__link">
            <i class="pagination-item__icon fas fa-angle-left"></i>
        </a>
    </li>

    <li class="pagination-item">
        <a href="https://localhost:44324/HomeUser/ThuongHieu?page=1" class="pagination-item__link">1</a>
    </li>
    <li class="pagination-item">
        <a href="https://localhost:44324/HomeUser/ThuongHieu?page=2" class="pagination-item__link">2</a>
    </li>
    <li class="pagination-item">
        <a href="https://localhost:44324/HomeUser/ThuongHieu?page=3" class="pagination-item__link">3</a>
    </li>
    <li class="pagination-item">
        <a href="#" class="pagination-item__link">...</a>
    </li>

    <li class="pagination-item">
        <a href="#" class="pagination-item__link">
            <i class="pagination-item__icon fas fa-angle-right"></i>
        </a>
    </li>
</ul>

WebDongHo/Views/HomeUser/TinTuc1.cshtml
@{
    ViewBag.Title = "TinTuc1";
    Layout = "~/Views/Shared/_LayoutUsers.cshtml";
}



<link rel="stylesheet" href="~/Content/newspage.css" />
<h1>10/5 – 10/7: TẶNG VÍ DA FUJITA NHẬT CAO CẤP 1 TRIỆU KHI MUA CITIZEN NAM</h1>
<div class="container">
    <div class="row">
        <div class="col-1">
            <img src="~/images/news-1.jpg" alt="" class="newspage-img">
            <p>Từ ngày 10/05 – 10/07, Đồng Hồ 4AE x Citizen x Fujita ra mắt chương trình mua đồng hồ Citizen nam, tặng ngay ví da Fujita Nhật Bản cao cấp trị giá hơn 1 triệu. Số lượng quà tặng giới hạn và có thể kết thúc sớm hơn dự kiến. Cùng tham khảo mua sắm và nhận quà khủng ngay hôm nay.</p>
            <h3>CHƯƠNG TRÌNH MUA ĐỒNG HỒ CITIZEN, TẶNG VÍ DA CAO CẤP</h3>
            <p>Citizen được biết đến là thương hiệu đồng hồ Nhật Bản hàng đầu với lượng khách hàng lớn trong khi Fujita cũng là thương hiệu ví cao cấp được thiết kế theo phong cách Nhật Bản.</p>
            <p>Sự kết hợp giữa thương hiệu đồng hồ Nhật Bản và thương hiệu ví da cao cấp theo phong cách Nhật Bản sẽ là Combo hấp dẫn. Tất cả sẽ được miễn phí khi mua sắm tại hệ thống Đồng Hồ 4AE.</p>
            <p>Chương trình mua đồng hồ, tặng ví da:</p>
            <p>● Thương hiệu áp dụng: Citizen – chỉ áp dụng đối với đồng hồ nam Citizen</p>
            <p>● Thương hiệu quà tặng: Fujita – Thương hiệu giày da Việt Nam</p>
            <p>● Thời gian áp dụng: 10/05 – 10/07/2021</p>
            <p>● Thông tin về quà tặng: Ví da sử dụng dòng da cao cấp nhập khẩu từ Ý, Pháp, Nhật,… sau đó gia công thủ công tại Việt Nam theo tiêu chuẩn của Nhật Bản.</p>
            <p>● Giá trị quà tặng: Quà tặng ví da Fujita cao cấp Nhật Bản có trị giá trên thị trường là hơn 1 triệu và là phiên bản giới hạn được phối hợp giữa 4AE x Fujita.</p>
            <hr>
            <p><h5>Còn gì hấp dẫn hơn khi tự do mua sắm mẫu đồng hồ Citizen nam yêu thích, vừa được tặng ví da cao cấp mà nam giới nào cũng cần!</h5></p>
            <hr>
            <img src="~/images/news-1.1.jpg" alt="" class="newspage-img">
            <p><h5>Quà tặng cao cấp từ thương hiệu Fujita</h5></p>
        </div>
    </div>
</div>