WebDongHo/Controllers/NguoiDungController.cs
using Facebook;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebDongHo.Models;
using Newtonsoft.Json;
using System.Web.Security;

namespace WebDongHo.Controllers
{
    public class NguoiDungController : Controller
    {
        DBDongHoDataContext data = new DBDongHoDataContext();
        // GET: NguoiDung
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, User us)
        {
            var hoten = collection["HoTenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["MatKhau"];
            var nhaplaimatkhau = collection["NhapLaiMatKhau"];
           // var gioitinh = collection["GioiTinh"];
           // var diachi = collection["DiaChi"];
            var email = collection["Email"];
           // var dienthoai = collection["DienThoai"];
           // var ngaysinh = String.Format("{0:MM/đ/yyyy}", collection["NgaySinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên khách hàng không được để trống";
            }
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Phải nhập tên đăng nhập";
            }
            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Vui lòng nhập mật khẩu";
            }
            if (String.IsNullOrEmpty(nhaplaimatkhau))
            {
                ViewData["Loi4"] = "Vui lòng xác nhận lại mật khẩu";
            }
            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "Email không được để trống";
            }
            //if (String.IsNullOrEmpty(dienthoai))
            //{
            //    ViewData["Loi6"] = "Vui lòng nhập SDT";
            //}
            //if (String.IsNullOrEmpty(ngaysinh))
            //{
            //    ViewData["Loi7"] = "Vui lòng nhập ngày sinh";
            //}
            else
            {
                us.HoTen = hoten;
                us.TaiKhoan = tendn;
                us.MatKhau = matkhau;
                us.Email = email;
               
               // us.GioiTinh = gioitinh;
               // us.DiaChi = diachi;
               // us.SDT = dienthoai;
               // us.NgaySinh =DateTime.Parse(ngaysinh);
                data.Users.InsertOnSubmit(us);
                data.SubmitChanges();
                return RedirectToAction("DangNhap");
            }
            return this.DangKy();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {

            
            var tendn = collection["TenDN"];
            var matkhau = collection["MatKhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
                User us = data.Users.SingleOrDefault(p => p.TaiKhoan == tendn && p.MatKhau == matkhau);
                if (us!=null)
                {               
                    Session["TaiKhoan"] = us;
                    return RedirectToAction("Index", "HomeUser");
                }
                else
                {
                    ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
               
            }
            return View();
        }
      
        public ActionResult LogOff() 
        {
            Session["TaiKhoan"] = null;

            return RedirectToAction("Index", "HomeUser");
        }

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        [AllowAnonymous]
        public ActionResult LoginFB()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                Redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });
            return Redirect(loginUrl.AbsoluteUri);
        }

        public ActionResult FacebookCallback(string code)
        {
            if (code == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var fb = new FacebookClient();

            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });
            var accessToken = result.access_token;
            Session["AccessToken"] = accessToken;
            fb.AccessToken = accessToken;
            dynamic me = fb.Get("me?fields=link,first_name,currency,last_name,email,gender,locale,timezone,verified,picture,age_range");
            string email = me.email;
            TempData["email"] = me.email;
            TempData["first_name"] = me.first_name;
            TempData["lastname"] = me.last_name;
            TempData["picture"] = me.picture.data.url;
            FormsAuthentication.SetAuthCookie(email, false);
            return RedirectToAction("Index", "Home");
        }


    }
}

WebDongHo/Views/NguoiDung/DangKy.cshtml
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_LayoutUsers.cshtml";
}
<link rel="stylesheet" href="~/Content/user.css" />

<div class="container">
    
    <div class="row">
        <div class="col-2">

        </div>
        <div class="col-2">
            <form action="" method="POST" class="form" id="form-1">
                <h3 class="heading">Đăng ký thành viên</h3>
                <p class="desc">Chào mừng bạn đến với cửa hàng</p>

                <div class="spacer"></div>

                <div class="form-group">
                    <label for="fullname" class="form-label">Họ tên</label>
                    <input id="" name="HoTenKH" type="text" placeholder="VD: Nguyễn Đức Long" class="form-control">

                    <span class="form-message"></span>
                </div>

                <div class="form-group">
                    <label for="fullname" class="form-label">Tên đăng nhập</label>
                    <input id="fullnamelogin" name="TenDN" type="text" placeholder="VD: DucLong123" class="form-control" required>
                    <span class="form-message"></span>
                </div>

                <div class="form-group">
                    <label for="email" class="form-label">Email</label>
                    <input id="email" name="Email" type="text" placeholder="VD: email@gmail.com" class="form-control" required>

                    <span class="form-message"></span>
                </div>

                <div class="form-group">
                    <label for="password" class="form-label">Mật khẩu</label>
                    <input id="password" name="MatKhau" type="password" placeholder="Nhập mật khẩu" class="form-control" required>
                    <span class="form-message"></span>
                </div>

                <div class="form-group">
                    <label for="password_confirmation" class="form-label">Nhập lại mật khẩu</label>
                    <input id="password_confirmation" name="NhapLaiMatKhau" placeholder="Nhập lại mật khẩu" type="password" class="form-control" required>
                    <span class="form-message"></span>
                </div>

                <button type="submit" class="form-submit">Đăng ký</button>


            </form>
        </div>
    </div>
</div>

WebDongHo/Views/NguoiDung/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_LayoutUsers.cshtml";
}

<h4 style="color:white;text-align:center">@ViewBag.ThongBao</h4>

<link rel="stylesheet" href="~/Content/user.css" />

    <div class="container">
        <div class="row">
            <div class="col-2">

            </div>
            <div class="col-2">
                <form action="" method="POST" class="form" id="form-2">
                    <h3 class="heading">Đăng Nhập</h3>
                    <p class="desc">Chào mừng bạn đến với cửa hàng</p>

                    <div class="spacer"></div>

                    <div class="form-group">
                        <label for="fullname" class="form-label">Tên đăng nhập</label>
                        <input id="fullnamelogin" name="TenDN" type="text" placeholder="VD: DucLong123" class="form-control">

                        <span class="form-message"></span>
                    </div>

                    <div class="form-group">
                        <label for="password" class="form-label">Mật khẩu</label>
                        <input id="password" name="MatKhau" type="password" placeholder="Nhập mật khẩu" class="form-control">
                        <span class="form-message"></span>
                    </div>


                    <button class="form-submit">Đăng Nhập</button>
                    <a href="@Url.Action("DangKy", "NguoiDung")" class="form-submit">Đăng Ký</a>
                    <br />
                    <p style="color:white"> Hoặc có thể đăng nhập bằng</p>
                    <button class="form-submit" style="background: #0e8ef2">
                        @Html.ActionLink("Facebook", "LoginFB", "NguoiDung")                       
                    </button>            
                    

                   

                </form>
            </div>
        </div>

    </div>