WebDongHo/Controllers/DonDatHangAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDongHo.Models;

namespace WebDongHo.Controllers
{
    public class DonDatHangAdminController : Controller
    {
        // GET: DonDatHangAdmin
        DBDongHoDataContext db = new DBDongHoDataContext();
        public ActionResult Index()
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            return View(db.DONDATHANGs.ToList());
        }
        public ActionResult ChiTietDatHang()
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            return View(db.CHITIETDONHANGs.ToList());
        }
    }
}

WebDongHo/Controllers/HomeUserController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDongHo.Models;
using PagedList;
namespace WebDongHo.Controllers
{
    public class HomeUserController : Controller
    {
        DBDongHoDataContext data = new DBDongHoDataContext();
        // GET: HomeUser
        
        public List<SanPham> SanPhamMoi(int count)
        {
            return data.SanPhams.OrderByDescending(a => a.NgayCapNhap).Take(count).ToList();
        }
        public ActionResult Index()
        {
            var spmoi = SanPhamMoi(4);       
            return View(spmoi);
        }
        public IEnumerable<SanPham> ListAllPage(string searchString, int page, int pageSize)
        {
        
            IQueryable<SanPham> model = data.SanPhams;
            if (!String.IsNullOrEmpty(searchString))
            {
                model = model.Where(s => s.TenSanPham.Contains(searchString) || s.MoTaNgan.Contains(searchString));
            }
            return model.OrderByDescending(x => x.NgayCapNhap).ToPagedList(page, pageSize);
        }
        public ActionResult SPNu()
        {
            var clients = from c in data.SanPhams
                          where c.TenSanPham.Contains("Nữ")
                          select c;
            return PartialView(clients);
        }

        public ActionResult SPNam()
        {
            var clients = from c in data.SanPhams
                          where c.TenSanPham.Contains("Nam")
                          select c;
            return PartialView(clients);
        }
        public ActionResult DanhMucSanPham()
        {
            var danhmuc = from dm in data.DanhMucSanPhams select dm;
            return PartialView(danhmuc);
        }
        public ActionResult DanhMucThuongHieu(int id)
        {
            var sp = from s in data.SanPhams
                     where s.MaDanhMuc == id
                     select s;
            ViewBag.TenTH = (from th in data.DanhMucSanPhams
                             where th.MaDanhMuc == id
                             select th);
            return View(sp);

        }
        public ActionResult Detail(int id)
        {
            var sp = from s in data.SanPhams
                     where s.MaSanPham == id
                     select s;
            
            ViewBag.SP_Khac = (from c in data.SanPhams
                               where c.MaDanhMuc != id                        
                               select c).ToList().Take(4);
            return View(sp.Single());
        }

        [HttpGet]
        public ActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Contact(FormCollection f,LienHe lh)
        {
            var Hoten = f["HoTen"];
            var Email = f["Email"];
            var Chude = f["ChuDe"];
            var Noidung = f["NoiDung"];
            if(String.IsNullOrEmpty(Hoten))
            {
                ViewData["Loi1"] = "Họ tên không được để trống";
            }
            else if (String.IsNullOrEmpty(Email))
            {
                ViewData["Loi2"] = "Email không được để trống";
            }
            else if (String.IsNullOrEmpty(Chude))
            {
                ViewData["Loi3"] = "Chủ đề không được để trống";
            }
            else if (String.IsNullOrEmpty(Noidung))
            {
                ViewData["Loi4"] = "Nội dung không được để trống";
            }
            else
            {
                lh.HoTen = Hoten;
                lh.Email = Email;
                lh.ChuDe = Chude;
                lh.NoiDung = Noidung;
                data.LienHes.InsertOnSubmit(lh);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Contact();  
        }        
        public ActionResult ThuongHieu(/*string searchString, int page = 1, int pageSize = 10*/ int? page)
        {
            var sp = from s in data.SanPhams select s;


            int pageNumber = (page ?? 1);
            int pageSize = 8;

            //ViewBag.TimKiem = ListAllPage(searchString, page, pageSize);

            //return View(sp);
            
            return View(data.SanPhams.ToList().OrderBy(n => n.MaSanPham).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Search(string searching)
        {
            //Lấy ra danh sách sản phẩm từ chuỗi tìm kiếm truyền vào
            var sp = from s in data.SanPhams select s;     
            ViewBag.TuKhoa = searching;

            return View(data.SanPhams.Where(x=>x.TenSanPham.Contains(searching) ||  searching == null).ToList());
        }
        public ActionResult Nu()
        {
            var clients = from c in data.SanPhams
                          where c.TenSanPham.Contains("Nữ")
                          select c;
            return View(clients);
        }

        public ActionResult Nam()
        {
            var clients = from c in data.SanPhams
                          where c.TenSanPham.Contains("Nam")
                          select c;
            return View(clients);
        }
        public ActionResult TinTuc()
        {     
            return View();
        }

        public ActionResult TinTuc1()
        {
            return View();
        }

        public ActionResult TinTuc2()
        {
            return View();
        }

        public ActionResult TinTuc3()
        {
            return View();
        }

        public ActionResult TinTuc4()
        {
            return View();
        }

        public ActionResult TinTuc5()
        {
            return View();
        }

        public ActionResult TinTuc6()
        {
            return View();
        }
        public ActionResult Payment()
        {
            //request params need to request to MoMo system
            string endpoint = "https://test-payment.momo.vn/gw_payment/transactionProcessor";
            string partnerCode = "MOMO2C5U20210720";
            string accessKey = "xTyRu9YtM0I082Z7";
            string serectkey = "bNjdi5w3IoG1fhVZbFPCDy5dUkfLZH0i";
            string orderInfo = "test";
            string returnUrl = "https://localhost:44324/HomeUser/ConfirmPaymentClient";
            string notifyurl = "https://localhost:44324/HomeUser/SavePayment"; 

            string amount = TongTien().ToString();
            string orderid = DateTime.Now.Ticks.ToString();
            string requestId = DateTime.Now.Ticks.ToString();
            string extraData = "";

            //Before sign HMAC SHA256 signature
            string rawHash = "partnerCode=" +
                partnerCode + "&accessKey=" +
                accessKey + "&requestId=" +
                requestId + "&amount=" +
                amount + "&orderId=" +
                orderid + "&orderInfo=" +
                orderInfo + "&returnUrl=" +
                returnUrl + "&notifyUrl=" +
                notifyurl + "&extraData=" +
                extraData;

            Momo crypto = new Momo();
            //sign signature SHA256
            string signature = crypto.signSHA256(rawHash, serectkey);

            //build body json request
            JObject message = new JObject
            {
                { "partnerCode", partnerCode },
                { "accessKey", accessKey },
                { "requestId", requestId },
                { "amount", amount },
                { "orderId", orderid },
                { "orderInfo", orderInfo },
                { "returnUrl", returnUrl },
                { "notifyUrl", notifyurl },
                { "extraData", extraData },
                { "requestType", "captureMoMoWallet" },
                { "signature", signature }

            };

            string responseFromMomo = PaymentRequest.sendPaymentRequest(endpoint, message.ToString());

            JObject jmessage = JObject.Parse(responseFromMomo);

            return Redirect(jmessage.GetValue("payUrl").ToString());
        }
        public List<Giohang> Laygiohang()
        {
            List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            if (lstGiohang == null)
            {
                lstGiohang = new List<Giohang>(); Session["Giohang"] = lstGiohang;
            }
            return lstGiohang;
        }
        public int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                iTongSoLuong = lstGiohang.Sum(n => n.iSoluong);
            }
            return iTongSoLuong;
        }
        public double TongTien()
        {
            double iTongTien = 0;
            List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                iTongTien = lstGiohang.Sum(n => n.dThanhtien);
            }
            return iTongTien;
        }


        public ActionResult ConfirmPaymentClient()
        {
            if (!Request.QueryString["errorCode"].Equals("0"))
            {
                Session["or"] = null;
                Session["lst"] = null;
                ViewBag.mess = "Thanh Toán thất bại";
            }
            else
            {
                ViewBag.mess = "Thanh toán thành công";
                SavePayment();
                Session["Giohang"] = null;
            }
            return View();
        }
     
        public void SavePayment()
        {         
            //DONDATHANG order = (DONDATHANG)Session["or"];
            //data.DONDATHANGs.InsertOnSubmit(order);
            //data.SubmitChanges();
            //List<CHITIETDONHANG> lst = (List<CHITIETDONHANG>)Session["lst"];
            //foreach (var item in lst)
            //{
            //    item.MaDonHang = order.MaDonHang;
            //    data.CHITIETDONHANGs.InsertOnSubmit(item);

WebDongHo/Controllers/NguoiDungController.cs
using Facebook;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebDongHo.Models;
using Newtonsoft.Json;
using System.Web.Security;

namespace WebDongHo.Controllers
{
    public class NguoiDungController : Controller
    {
        DBDongHoDataContext data = new DBDongHoDataContext();
        // GET: NguoiDung
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, User us)
        {
            var hoten = collection["HoTenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["MatKhau"];
            var nhaplaimatkhau = collection["NhapLaiMatKhau"];
           // var gioitinh = collection["GioiTinh"];
           // var diachi = collection["DiaChi"];
            var email = collection["Email"];
           // var dienthoai = collection["DienThoai"];
           // var ngaysinh = String.Format("{0:MM/đ/yyyy}", collection["NgaySinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên khách hàng không được để trống";
            }
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Phải nhập tên đăng nhập";
            }
            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Vui lòng nhập mật khẩu";
            }
            if (String.IsNullOrEmpty(nhaplaimatkhau))
            {
                ViewData["Loi4"] = "Vui lòng xác nhận lại mật khẩu";
            }
            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "Email không được để trống";
            }
            //if (String.IsNullOrEmpty(dienthoai))
            //{
            //    ViewData["Loi6"] = "Vui lòng nhập SDT";
            //}
            //if (String.IsNullOrEmpty(ngaysinh))
            //{
            //    ViewData["Loi7"] = "Vui lòng nhập ngày sinh";
            //}
            else
            {
                us.HoTen = hoten;
                us.TaiKhoan = tendn;
                us.MatKhau = matkhau;
                us.Email = email;
               
               // us.GioiTinh = gioitinh;
               // us.DiaChi = diachi;
               // us.SDT = dienthoai;
               // us.NgaySinh =DateTime.Parse(ngaysinh);
                data.Users.InsertOnSubmit(us);
                data.SubmitChanges();
                return RedirectToAction("DangNhap");
            }
            return this.DangKy();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {

            
            var tendn = collection["TenDN"];
            var matkhau = collection["MatKhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
                User us = data.Users.SingleOrDefault(p => p.TaiKhoan == tendn && p.MatKhau == matkhau);
                if (us!=null)
                {               
                    Session["TaiKhoan"] = us;
                    return RedirectToAction("Index", "HomeUser");
                }
                else
                {
                    ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
               
            }
            return View();
        }
      
        public ActionResult LogOff() 
        {
            Session["TaiKhoan"] = null;

            return RedirectToAction("Index", "HomeUser");
        }

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        [AllowAnonymous]
        public ActionResult LoginFB()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                Redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });
            return Redirect(loginUrl.AbsoluteUri);
        }

        public ActionResult FacebookCallback(string code)
        {
            if (code == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var fb = new FacebookClient();

            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });
            var accessToken = result.access_token;
            Session["AccessToken"] = accessToken;
            fb.AccessToken = accessToken;
            dynamic me = fb.Get("me?fields=link,first_name,currency,last_name,email,gender,locale,timezone,verified,picture,age_range");
            string email = me.email;
            TempData["email"] = me.email;
            TempData["first_name"] = me.first_name;
            TempData["lastname"] = me.last_name;
            TempData["picture"] = me.picture.data.url;
            FormsAuthentication.SetAuthCookie(email, false);
            return RedirectToAction("Index", "Home");
        }


    }
}

WebDongHo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>

WebDongHo/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>

    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Light Bootstrap Dashboard - Free Bootstrap 4 Admin Dashboard by Creative Tim</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/light-bootstrap-dashboard.css?v=2.0.0 " rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="~/assets/css/demo.css" rel="stylesheet" />


</head>
<body>
    
    <div class="wrapper">
        <div class="sidebar" data-image="../assets/img/sidebar-5.jpg">
            <!--
            Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

            Tip 2: you can also add an image using data-image tag
        -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="" class="simple-text">
                        Quản Lý Danh Mục
                    </a>
                </div>
                <ul class="nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index","Admin")">
                            <i class="nc-icon nc-chart-pie-35"></i>
                            <p>Trang Chủ</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","TaiKhoan")">
                            <i class="nc-icon nc-circle-09"></i>
                            <p>Tài Khoản</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("QLSanPham","Admin")">
                            <i class="nc-icon nc-notes"></i>
                            <p>Quản Lý Sản Phẩm</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","ThuongHieu")">
                            <i class="nc-icon nc-paper-2"></i>
                            <p>Quản Lý Thương Hiệu</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","LienHe")">
                            <i class="nc-icon nc-paper-2"></i>
                            <p>Quản Lý Liên Hệ</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("Index","DonDatHangAdmin")">
                            <i class="nc-icon nc-paper-2"></i>
                            <p>Quản Lý Đơn Hàng</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("ChiTietDatHang","DonDatHangAdmin")">
                            <i class="nc-icon nc-paper-2"></i>
                            <p>Chi Tiết Đơn Đặt Hàng</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class="container-fluid">
                    <a class="navbar-brand" href="" style="text-align: center; text-transform: uppercase; color: #ff9c27; "> Đồng Hồ 4 AE </a>
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">

                        @using WebDongHo.Models
                        <ul class="navbar-nav ml-auto">

                            <li class="nav-item">

                                <a class="nav-link" href="#pablo">

                                    <span class="no-icon">Xin chào: @Session["TaiKhoanAdmin"]</span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("LogOff","Admin")">
                                    <span class="no-icon">Đăng Xuất</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div>
                @RenderBody()
            </div>
        </div>
    </div>
</body>
<!--<script src="~/assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="~/assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="~/assets/js/core/bootstrap.min.js" type="text/javascript"></script>-->
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<!--<script src="~/assets/js/plugins/bootstrap-switch.js"></script>-->
<!--  Google Maps Plugin    -->
<!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>-->
<!--  Chartist Plugin  -->
<!--<script src="~/assets/js/plugins/chartist.min.js"></script>-->
<!--  Notifications Plugin    -->
<!--<script src="~/assets/js/plugins/bootstrap-notify.js"></script>-->
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<!--<script src="~/assets/js/light-bootstrap-dashboard.js?v=2.0.0 " type="text/javascript"></script>-->
<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
<!--<script src="~/assets/js/demo.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        // Javascript method's body can be found in assets/js/demos.js
        demo.initDashboardPageCharts();

        demo.showNotification();

    });
</script>-->
</html>